# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6c6433a57af405e854dea2d3d640960995b2f3015b8546b6cdd81e0fa65de52d55611a58fdddb9b2ca7aec8e7344c0a80697dd7e7a69488b4eae189d3a11d2a7

test:
  secret_key_base: cfe4ef06ae5065f6cd90a4f7a397673a144a5c2dc1715872c0b762e6ed900679f9594ccc3490beb42d8f19686b38df084e3350f5c4ddf5f8710ec69534b21c11

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
